# Generated by Django 4.2.27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("signals", "0002_signalreport_clustering_fields"),
    ]

    # Remove fields from Django model state only (columns kept in DB for rollback safety). This satisfies our migration risk checker.
    # The follow-up is to actually drop the columns after a full deploy cycle. Not important or urgent though.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="signalreport",
                    name="cluster_centroid",
                ),
                migrations.RemoveField(
                    model_name="signalreport",
                    name="cluster_centroid_updated_at",
                ),
            ],
            database_operations=[],
        ),
    ]
